# Generated by Django 5.1.3 on 2025-02-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botx_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedurl',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
